export const pricingDetails = {
  free: [
    "Limited Access to Basic Features",
    "No Monthly Subscription Fee",
    "Community Support",
    "Ad-supported Experience",
    "Standard Resolution",
    "Basic Analytics",
    "Up to 1 Project",
    "Regular Updates",
    "Email Notifications",
    "Access to Knowledge Base",
  ],
  pro: [
    "Full Access to All Features",
    "Monthly Subscription",
    "Priority Customer Support",
    "Ad-free Experience",
    "High-Resolution Content",
    "Advanced Analytics",
    "Up to 5 Projects",
    "Frequent Updates",
    "Email and Chat Support",
    "Access to Premium Resources",
  ],
  premium: [
    "VIP Access to Exclusive",
    "Premium Monthly Subscription",
    "Ad-free and Personalized",
    "Ultra-High-Resolution",
    "Advanced Analytics with Insights",
    "Unlimited Projects",
    "Early Access to New",
    "Priority Email, Chat",
    "Access to Premium",
  ],
};
